"""add stars column to feedback

Revision ID: 337aed1af62c
Revises: 02ea7bfaaa35
Create Date: 2026-09-11 09:40:30.410761+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '337aed1af62c'
down_revision: Union[str, None] = '02ea7bfaaa35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('stars', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'stars')
    # ### end Alembic commands ###
