"""add rebuild status tracking to settings

Revision ID: 02ea7bfaaa35
Revises: f85537965423
Create Date: 2026-09-07 15:15:17.395404+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02ea7bfaaa35'
down_revision: Union[str, None] = 'f85537965423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default='idle' ใส่เพิ่มเอง (autogenerate ไม่ใส่ให้) — จำเป็นเพราะคอลัมน์นี้เป็น
    # NOT NULL แต่ตาราง settings มีแถว "config" อยู่แล้วในระบบจริง ถ้าไม่มี default ตอน
    # ALTER TABLE ADD COLUMN จะ fail เพราะแถวเดิมไม่มีค่าให้คอลัมน์ใหม่
    op.add_column('settings', sa.Column('rebuild_status', sa.String(length=50), nullable=False, server_default='idle'))
    op.add_column('settings', sa.Column('rebuild_message', sa.Text(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'rebuild_message')
    op.drop_column('settings', 'rebuild_status')
    # ### end Alembic commands ###
