"""initial schema baseline

สร้างจาก autogenerate เทียบกับ app/models/models.py ปัจจุบัน (2026-09-07) — ครอบคลุมทั้ง
schema ตั้งต้นและ 4 คอลัมน์ที่เดิมเพิ่มด้วย ALTER TABLE ตรงๆ ใน core/database.py ตอน startup
(documents.uploaded_by, users.department, announcements.category, announcements.created_by)

หมายเหตุสำคัญสำหรับ production/test DB ที่มีตารางอยู่แล้วก่อนเปลี่ยนมาใช้ Alembic:
ห้ามรัน `alembic upgrade head` ตรงๆ เพราะจะพยายาม CREATE TABLE ที่มีอยู่แล้วแล้ว fail
ให้รัน `alembic stamp head` แทน (แปะ revision นี้ว่า "apply แล้ว" โดยไม่รัน SQL จริง)
ดู Backend/README ส่วน Database Migrations สำหรับขั้นตอนเต็ม

Revision ID: f85537965423
Revises:
Create Date: 2026-09-07 14:04:28.834090+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85537965423'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('start_date', sa.String(length=100), nullable=True),
    sa.Column('end_date', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('exclude_pages', sa.Text(), nullable=True),
    sa.Column('chunking_duration', sa.Float(), nullable=True),
    sa.Column('embedding_duration', sa.Float(), nullable=True),
    sa.Column('upload_date', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_filename'), 'documents', ['filename'], unique=True)
    op.create_table('forms',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('page', sa.String(length=50), nullable=True),
    sa.Column('download_link', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('chunk_ids', sa.Text(), nullable=True),
    sa.Column('api_model', sa.String(length=255), nullable=True),
    sa.Column('referenced_docs', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('embedding_tech', sa.String(length=50), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('chat_greeting', sa.Text(), nullable=True),
    sa.Column('custom_faqs', sa.Text(), nullable=True),
    sa.Column('predefined_faqs', sa.Text(), nullable=True),
    sa.Column('last_build_duration', sa.Float(), nullable=True),
    sa.Column('gemini_api_key', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unanswered',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('feedback',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.String(length=50), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('history_id', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['history_id'], ['history.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('unanswered')
    op.drop_table('settings')
    op.drop_table('history')
    op.drop_table('forms')
    op.drop_index(op.f('ix_documents_filename'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('announcements')
    # ### end Alembic commands ###
